import {HouseWithBuns, HouseWithBunsId} from "../types/Buns.ts";
import {hashThatString} from "../utilities/Strings.ts";

const placesWithBuns: HouseWithBuns[] = [
    {
        name: "AS Frichs Conditori",
        description: 'Litt old-fashion cafè og bakevarestopp. Det er ikke så mange andre steder i området her for en stopp av bakevarer laget lokalt. Bolle med sjokoladetrekk er ofte en schlagers.',
        comment: '',
        city: 'Dombås',
        visited: [new Date()],
        by: '@vegaasen',
        rating: 3,
        pictures: [],
        features: ['Parkering', 'Sitteområde', 'Toalett'],
        servings: ['brød', 'vafler', 'kaffe', 'påsmurt', 'rundstykker', 'kanelboller'],
        marker: {latitude: 62.074635, longitude: 9.1228863},
        www: '',
        added: new Date(),
    },
    {
        name: "Mjonøy",
        description: 'Fantastisk liten pærle midt i Telemark på veien mot vestlandet/østlandet. Mye spennende smaker her, både det som er å få kjøpt i "baksthuset", og det som er tilbys av mat laget der. Ofte forskjellige boller og brød tilgjengelig. Parkeringen er bra. Verdt en stopp!',
        comment: '',
        city: 'Vinjesvingen',
        visited: [new Date()],
        by: '@vegaasen',
        rating: 5,
        pictures: [],
        features: ['Parkering', 'Sitteområde', 'Toalett'],
        servings: ['brød', 'kaffe', 'påsmurt', 'rundstykker', 'fancy-snurrer', 'vaniljesnurrer', 'kanelsnurrer'],
        marker: {latitude: 59.6344, longitude: 7.7982327},
        www: '',
        added: new Date(),
    },
    {
        name: "Bakeri Nansen",
        description: 'Det er knapt bedre bakevarer å oppdrive langs veien. Mye spennende smaker i form av boller, vafler og andre bakevarer. Anbefales en stopp. God parkering enten man kommer fra aust eller vest. Bakevarene blir fort utsolgt, så vær kjapp! De åpner ofte i 11-draget.',
        comment: '',
        city: 'Haukeliseter, Haukeli',
        visited: [new Date()],
        by: '@vegaasen',
        rating: 5,
        pictures: [],
        features: ['Parkering', 'Sitteområde', 'Toalett'],
        servings: ['brød', 'påsmurt', 'rundstykker', 'fancy-snurrer', 'vaniljesnurrer', 'kanelsnurrer', 'vafler'],
        marker: {latitude: 59.8237931, longitude: 7.1916304},
        www: '',
        added: new Date(),
    },
    {
        name: "Akerhaugen Gård",
        description: 'Trivelig stoppested som er på vei gjennom Telemarks flotte pærler. Dersom man er på vei fra Notodden til Bø, er dette en enkel og vel verdt omvei. Mye spennende utsalg, lokalt og omegn.',
        comment: '',
        city: 'Bø i Telemark',
        visited: [new Date()],
        by: '@vegaasen',
        rating: 4.5,
        pictures: [],
        features: ['Parkering', 'Sitteområde', 'Toalett'],
        servings: ['brød', 'påsmurt', 'rundstykker', 'fancy-snurrer', 'vaniljesnurrer', 'kanelsnurrer', 'vafler'],
        marker: {latitude: 59.396586, longitude: 9.118245},
        www: 'https://www.akerhaugengard.no/',
        added: new Date(),
    },
    {
        name: "Gardsbutikk. Gvarv Frukt og Bær",
        description: 'Flott og gode lokaler med mye spennende. Her er det bakstvarer og utsalg av lokale godheter',
        comment: '',
        city: 'Bø i Telemark',
        visited: [new Date()],
        by: '@vegaasen',
        rating: 4.5,
        pictures: [],
        features: ['Parkering', 'Sitteområde', 'Toalett'],
        servings: ['brød', 'påsmurt', 'rundstykker', 'fancy-snurrer', 'vaniljesnurrer', 'kanelsnurrer', 'vafler', 'diverse'],
        marker: {latitude: 59.396573, longitude: 9.1182449},
        www: '',
        added: new Date(),
    },
    {
        name: "Bø Brød",
        description: 'God bakst er viktig, og det finner man absolutt her. Ligger nærme Bø-senteret, så det er enkelt å finne frem, parkere o.l',
        comment: '',
        city: 'Bø i Telemark',
        visited: [new Date()],
        by: '@vegaasen',
        rating: 4.5,
        pictures: [],
        features: ['Parkering', 'Sitteområde', 'Toalett'],
        servings: ['brød', 'påsmurt', 'rundstykker', 'fancy-snurrer', 'vaniljesnurrer', 'kanelsnurrer', 'vafler', 'diverse'],
        marker: {latitude: 59.39656, longitude: 9.1182449},
        www: 'https://www.bobrod.no/',
        added: new Date(),
    },
    {
        name: "ELT bakeri",
        description: 'Mye spennende bakst fra dette bakeriet. Surdeigsbrødet er spesielt godt. Merk: dette er ikke et utsalgssted. Sjekk Joker Atnbrua eller Joker Folldal.',
        comment: '',
        city: 'Sollia',
        visited: [new Date()],
        by: '@vegaasen',
        rating: 5,
        pictures: [],
        features: [],
        servings: [],

        marker: {latitude: 61.6355067, longitude: 10.3340612},
        www: 'https://www.eltbakeri.no/',
        added: new Date(),
    },
    {
        name: "Bakeriet i Lom",
        description: 'Det skal litt til å ikke ha hørt om dette bakeriet gjennom jungeltelegraf eller lignende. Lever absolutt opp til ryktet sitt, og det blir servert nydelig bakst her.',
        comment: '',
        city: 'Lom',
        visited: [new Date()],
        by: '@vegaasen',
        rating: 5,
        pictures: [],
        features: ['Parkering', 'Sitteområde', 'Toalett'],
        servings: ['brød', 'påsmurt', 'rundstykker', 'fancy-snurrer', 'vaniljesnurrer', 'kanelsnurrer', 'vafler', 'diverse'],
        marker: {latitude: 61.8378516, longitude: 8.5648697},
        www: 'https://www.bakerietilom.no/',
        added: new Date(),
    },
    {
        name: "Eidum Gårdsbakeri",
        description: 'Mye god bakst å finne her. Alt fra boller til brød. Absolutt verdt en stopp på veien dersom en er i området.',
        comment: '',
        city: 'Stjørdal',
        visited: [new Date()],
        by: '@vegaasen',
        rating: 4.5,
        pictures: [],
        features: [],
        servings: [],
        marker: {latitude: 63.4435786, longitude: 10.9789545},
        www: 'https://eidum.no/',
        added: new Date(),
    },
    {
        name: "Øverland håndverksbakeri",
        description: 'Her er det mye forskjellig å velge i. Alt fra bakst til kaker, anbefaler å ta med en god del av begge deler!',
        comment: '',
        city: 'Gjemnes',
        visited: [new Date()],
        by: '@vegaasen',
        rating: 5,
        pictures: [],
        features: [],
        servings: [],
        marker: {latitude: 62.9277387, longitude: 7.6049291},
        www: 'https://øverlandhåndverksbakeri.no/',
        added: new Date(),
    },
    {
        name: "Fredag & Fretland Bakeri",
        description: 'Godt utvalg. Spesielt herlige boller og croissanter. Kjøpte også påsmurt rundstykker her, upåklagelig. Anbefales for stopp!',
        comment: '',
        city: 'Lærdal',
        visited: [new Date()],
        by: '@vegaasen',
        rating: 5,
        pictures: [],
        features: [],
        servings: [],

        marker: {latitude: 61.0974248, longitude: 7.4750224},
        www: 'https://www.fredagfretland.no/',
        added: new Date(),
    },
    {
        name: "Drivhuset Bageri & Gårdsutsalg",
        description: 'Herlig miks av litt forskjellig utsalg. Vi hadde lønsj her i samme slengen som god bakst ble fortært. Kommer absolutt tilbake',
        comment: '',
        city: 'Bryne',
        visited: [new Date()],
        by: '@vegaasen',
        rating: 4.5,
        pictures: [],
        features: [],
        servings: [],

        marker: {latitude: 58.7405474, longitude: 5.6899155},
        www: 'https://www.drivhusetbageri.no/',
        added: new Date(),
    },
    {
        name: "Molinå Bakery",
        description: 'Mye godt her inne, dersom man er en surdeigselsker. Det er heldigvis vi - så dette gikk rett hjem. Mye spennende prøvelser!',
        comment: '',
        city: 'Stavanger',
        visited: [new Date()],
        by: '@vegaasen',
        rating: 5,
        pictures: [],
        features: [],
        servings: [],

        marker: {latitude: 58.9710419, longitude: 5.7371277},
        www: 'https://www.molino-bakery.com/',
        added: new Date(),
    },
    {
        name: "THE ODD BAKERY AS",
        description: 'Stoppet innom for litt søt gjærbakst, og det ble ikke skuffende.',
        comment: '',
        city: 'Kristiansand',
        visited: [new Date()],
        by: '@vegaasen',
        rating: 5,
        pictures: [],
        features: [],
        servings: [],

        marker: {latitude: 58.1508821, longitude: 7.9935184},
        www: '',
        added: new Date(),
    },
    {
        name: "Farine",
        description: '',
        comment: '',
        city: '',
        visited: [new Date()],
        by: '@vegaasen',
        rating: 5,
        pictures: [],
        features: [],
        servings: [],

        marker: {latitude: 59.9115335, longitude: 10.7789724},
        www: '',
        added: new Date(),
    },
    {
        name: "BIT BYPORTEN",
        description: 'Tradisjonell BIT, på byporten/Oslo S. Veldig gode og digre boller, med alt for mye smør og sukker. Fantastisk!',
        comment: '',
        city: 'Oslo',
        visited: [new Date()],
        by: '@vegaasen',
        rating: 4.5,
        pictures: [],
        features: [],
        servings: [],

        marker: {latitude: 59.9117412, longitude: 10.7483199},
        www: '',
        added: new Date(),
    },
    {
        name: "Harmoni Håndverksbakeri AS",
        description: '',
        comment: '',
        city: '',
        visited: [new Date()],
        by: '@vegaasen',
        rating: 5,
        pictures: [],
        features: [],
        servings: [],

        marker: {latitude: 59.1396618, longitude: 9.6507114},
        www: '',
        added: new Date(),
    },
    {
        name: "Bollebar",
        description: '',
        comment: '',
        city: '',
        visited: [new Date()],
        by: '@vegaasen',
        rating: 5,
        pictures: [],
        features: [],
        servings: [],

        marker: {latitude: 59.9111776, longitude: 10.7247522},
        www: '',
        added: new Date(),
    },
    {
        name: "Byrkjedalstunet",
        description: '',
        comment: '',
        city: '',
        visited: [new Date()],
        by: '@vegaasen',
        rating: 5,
        pictures: [],
        features: [],
        servings: [],

        marker: {latitude: 58.7796544, longitude: 6.3139549},
        www: '',
        added: new Date(),
    },
    {
        name: "Bakergaarden Café",
        description: '',
        comment: '',
        city: '',
        visited: [new Date()],
        by: '@vegaasen',
        rating: 5,
        pictures: [],
        features: [],
        servings: [],

        marker: {latitude: 59.481309, longitude: 11.6519671},
        www: '',
        added: new Date(),
    },
    {
        name: "Fattigmann",
        description: '',
        comment: '',
        city: 'Kongsberg',
        visited: [new Date()],
        by: '@vegaasen',
        rating: 4,
        pictures: [],
        features: [],
        servings: [],

        marker: {latitude: 59.6702831, longitude: 9.6493556},
        www: '',
        added: new Date(),
    },
    {
        name: "Go'baksten Saltnes bakeri",
        description: '',
        comment: '',
        city: 'Etne',
        visited: [new Date()],
        by: '@vegaasen',
        rating: 4.5,
        pictures: [],
        features: [],
        servings: [],

        marker: {latitude: 59.6649078, longitude: 5.93789},
        www: '',
        added: new Date(),
    },
    {
        name: "Fløy Bakeri",
        description: '',
        comment: '',
        city: '',
        visited: [new Date()],
        by: '@vegaasen',
        rating: 5,
        pictures: [],
        features: [],
        servings: [],

        marker: {latitude: 60.3248895, longitude: 6.6437535},
        www: '',
        added: new Date(),
    },
    {
        name: "Flåm Bakeri",
        description: '',
        comment: '',
        city: 'Flåm',
        visited: [new Date()],
        by: '@vegaasen',
        rating: 4.5,
        pictures: [],
        features: [],
        servings: [],

        marker: {latitude: 60.8631545, longitude: 7.0855947},
        www: '',
        added: new Date(),
    },
    {
        name: "La Boulangerie",
        description: 'Liten de-tour fra veien til vestlandet eller sørlandet så ligger dette stedet. Godt utvalg og gode priser - bra kaffe! Er litt fransk-inspirert, sier de selv, men de har egentlig mye god bakst som minner mer om det skandinaviske bakekjøkken. Verdt en stopp dersom de er åpne! God parkering.',
        comment: '',
        city: 'Drammen',
        visited: [new Date()],
        by: '@vegaasen',
        rating: 4.5,
        pictures: [],
        features: [],
        servings: [],

        marker: {latitude: 59.7424861, longitude: 10.1712757},
        www: '',
        added: new Date(),
    },
    {
        name: "Trolltunga lille bakeri",
        description: 'Tradisjonelt bakeri som er gode på bakst, kaker og lignende. Nesten det eneste bakeriet i Odda og ligger bra til mtp. stoppested.',
        comment: '',
        city: 'Odda',
        visited: [new Date()],
        by: '@vegaasen',
        rating: 4,
        pictures: [],
        features: ['Parkering', 'Sitteområde', 'Toalett'],
        servings: ['brød', 'påsmurt', 'rundstykker', 'fancy-snurrer', 'vaniljesnurrer', 'kanelsnurrer', 'vafler', 'diverse', 'kaker'],
        marker: {latitude: 60.0702119, longitude: 6.5038972},
        www: '',
        added: new Date(),
    },
    {
        name: "Á Tartiner Bakeri",
        description: 'Godt utvalg av bakevarer, og ligger bra til mtp. parkering og dersom man er på vei fra/til Hardangervidda.',
        comment: '',
        city: 'Geilo',
        visited: [new Date()],
        by: '@vegaasen',
        rating: 4,
        pictures: [],
        features: ['Parkering', 'Sitteområde'],
        servings: ['brød', 'påsmurt', 'rundstykker', 'fancy-snurrer', 'vaniljesnurrer', 'kanelsnurrer', 'diverse', 'kaker', 'pizza'],
        marker: {latitude: 60.5344728, longitude: 8.2117614},
        www: '',
        added: new Date(),
    },
    {
        name: "Lilleholmestrand Kaffebar",
        description: 'Flott sted for god bakst i farten. Stoppet her mange ganger som kjørende og som syklende. Blir nok flere stopp også i fremtiden.',
        comment: '',
        city: 'Holmestrand',
        visited: [new Date()],
        by: '@vegaasen',
        rating: 4,
        pictures: [],
        features: ['Parkering', 'Sitteområde'],
        servings: ['brød', 'påsmurt', 'rundstykker', 'fancy-snurrer', 'vaniljesnurrer', 'kanelsnurrer', 'diverse', 'kaker', 'pizza'],
        marker: {latitude: 59.489011, longitude: 10.3130326},
        www: '',
        added: new Date(),
    },
    {
        name: "Nøtterø Bakeri & Konditori",
        description: 'Godt utvalg av mye forskjellig, også litt lokalbakst som en ikke finner andre steder. Stoppet her mange ganger på sykkel og i bil. Blir flere stopp!',
        comment: '',
        city: 'Tjøme',
        visited: [new Date()],
        by: '@vegaasen',
        rating: 4,
        pictures: [],
        features: ['Parkering', 'Sitteområde'],
        servings: ['brød', 'påsmurt', 'rundstykker', 'fancy-snurrer', 'vaniljesnurrer', 'kanelsnurrer', 'diverse', 'kaker', 'pizza'],
        marker: {latitude: 59.1082235, longitude: 10.4120776},
        www: 'https://nottero-bakeri.no/',
        added: new Date(),
    },
]

export const fetchAllTheBuns = async (): Promise<HouseWithBunsId[]> => Promise.resolve(placesWithBuns.map(place => ({...place, id: hashThatString(place.name)})))
